### ISSUE TITLE
Workflow 中无法编译通过

### ISSUE THREAD

**Issue by raiots** [mnixry/python-orb-slam3#2]
首先感谢作者的贡献～

目前存在如下问题：workflow 中 windows 平台下无法成功编译 opencv。

在 workflow 文件中删除 Windows 平台下验证后会在  Build Wheel 步骤报错如下：
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'orb_slam3'
```

btw，请问为什么在 pypi 上搜不到这个包呀？

**Comment by mnixry** [comment]
> 首先感谢作者的贡献～
> 
> 目前存在如下问题：workflow 中 windows 平台下无法成功编译 opencv。

确实是，我不知道是啥问题，感觉很玄学，明天看看

> 在 workflow 文件中删除 Windows 平台下验证后会在 Build Wheel 步骤报错如下：
> 
> ```
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
> ModuleNotFoundError: No module named 'orb_slam3'
> ```

我试试复现一下，不应该有这个问题的

上面两个问题你试试先把OpenCV版本锁 4.6.0 编译，应该不会有问题，我当时编译过了的时候就用的 4.6.0

> btw，请问为什么在 pypi 上搜不到这个包呀？

~~因为我忘记发了~~ 没想好这个包发布该怎么写自动化

**Comment by mnixry** [comment]
Fixed in https://github.com/mnixry/python-orb-slam3/commit/e7e00a5f5f4c21e094e6f99e39d399728e6f3c8a
